### ISSUE TITLE
How to pass .text variable to IText from program side?

### ISSUE THREAD

**Issue by monocraft** [wieslawsoltes/RxCanvas#4]
I was just found your RxCanvas and it is very intuitive.
I would love if you can demonstrate how to pass .text variable to your IText child from code side?

**Comment by wieslawsoltes** [comment]
You can not create IText object directly. You have to use XText concrete implementation.
You can find example here:
https://github.com/wieslawsoltes/RxCanvas/blob/master/RxCanvas.Shared/Shared/Editors.cs#L1838

**Comment by monocraft** [comment]
I tried something like this but i lost the ability to select it.  Any hint?  - Additionally it seems like the PDF export doesn't work at all.    
        /////////////////////
            var textx2 = new XText()
            {
                Point1 = new XPoint(10.0, 10.0),
                Point2 = new XPoint(200.0, 200.0),
                HorizontalAlignment = 1,
                VerticalAlignment = 1,
                Size = 24.0,
                Text = "This is my text",
                Foreground = new XColor(0xFF, 0x00, 0x00, 0x00),
                Backgroud = new XColor(0x00, 0xFF, 0xFF, 0xFF),
            };


            textx2.Point1.Connected.Add(textx2);
            textx2.Point2.Connected.Add(textx2);
            Children.Add(textx2);

**Comment by monocraft** [comment]
I was able to find out why PDF export was not working.
Creators was not registered.
Let me know if you can give me some hint on how to code text and still able to move it from canvas.
Thanks Wieslaw

**Comment by wieslawsoltes** [comment]
Try this code:
https://github.com/monocraft/RxCanvas/blob/master/RxCanvas.Shared/Shared/Editors.cs#L1602

**Comment by wieslawsoltes** [comment]
For you information, I do not develop anymore this project and have not plans in future.

I have very similar project, which in part based on this project.

Plese try this:
https://github.com/wieslawsoltes/Test2d

The `Test2d` project is much easier to code.

**Comment by monocraft** [comment]
Thank you Wieslaw.
Test2d is very in-dept.  I am hoping it support code side drawing as I want to layout some default text on the viewingboard.
